update unrelated history

diff --git a/.github/workflows/update-model-version.yaml b/.github/workflows/update-model-version.yaml
--- a/.github/workflows/update-model-version.yaml
+++ b/.github/workflows/update-model-version.yaml
@@ -46,7 +46,7 @@ jobs:
                   echo "Directory $new_cache_directory created."
           
                   # Copy all files from the previous version into the new folder
-                  cp -r "$cache/$key/$current_version/"* "$new_cache_directory/"
+                  cp -r "cache/$key/$current_version/"* "$new_cache_directory/"
                   # Copy(overwrite) all existing contents into the new folder   
                   cp -r "$model_path/"* "$new_cache_directory/"
                   echo "Copied contents from $model_path to cache/$key/$new_cache_directory."
@@ -98,4 +98,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
+          # ...|| true part ensures that even if the pull fails, the script continues to the push step.
+          git pull origin ${{ github.ref_name }} --allow-unrelated-histories || true
           git push origin ${{ github.ref_name }}
